# Generated by Django 2.0.3 on 2020-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200614_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
