# Generated by Django 2.0.3 on 2020-06-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200615_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
