# Generated by Django 2.0.3 on 2020-06-15 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200615_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.IntegerField()),
                ('price', models.FloatField(max_length=4)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sizes')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pizzas')),
            ],
        ),
    ]
