# Generated by Django 3.0.7 on 2020-06-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='toppings',
        ),
        migrations.AlterField(
            model_name='sub',
            name='price',
            field=models.FloatField(max_length=4),
        ),
    ]
