# Generated by Django 3.0.7 on 2020-06-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200615_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastaprotein',
            old_name='name',
            new_name='protein',
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(max_length=4),
        ),
    ]
