# Generated by Django 3.0.7 on 2020-06-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200615_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizzas',
            new_name='Pizza_style',
        ),
    ]
