# Generated by Django 3.0.7 on 2020-06-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200615_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Pasta_type',
        ),
        migrations.RenameModel(
            old_name='Platters',
            new_name='Platter_type',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.RenameModel(
            old_name='Pastas',
            new_name='Sub_type',
        ),
        migrations.RenameModel(
            old_name='Subs',
            new_name='Topping',
        ),
        migrations.RenameField(
            model_name='pasta_type',
            old_name='toppings',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub_type',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='type',
            new_name='topping',
        ),
    ]
