# Generated by Django 3.0.7 on 2020-06-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200617_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.ManyToManyField(blank=True, to='orders.Pasta')),
                ('pizza', models.ManyToManyField(blank=True, to='orders.Pizza')),
                ('platters', models.ManyToManyField(blank=True, to='orders.Platter')),
                ('salads', models.ManyToManyField(blank=True, to='orders.Salad')),
                ('subs', models.ManyToManyField(blank=True, to='orders.Sub')),
            ],
        ),
    ]
